accounts/urls.py
from django.urls import path
from .views import SignUpView
app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetail, BlogCreateView, BlogUpdateView, BlogDeleteView
urlpatterns = [
    path('',BlogListView.as_view(), name='home'),
    path('blog/<int:pk>/', BlogDetail.as_view(), name='blog'),
    path('new_blog/', BlogCreateView.as_view(), name='new_blog'),
    path('blog/<int:pk>/edit/', BlogUpdateView.as_view(), name='update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),# for user login,signups,logouts
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = models.TextField()
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self): 
        return reverse("blog", kwargs={"pk": self.pk})
    
    # its best practice to add the above two methods to every model

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Blog
from django.urls import reverse_lazy
# Create your views here.
class BlogListView(ListView):
    model = Blog
    template_name = "home.html"
    context_object_name = 'blogs'
    

class BlogDetail(DetailView):
    model = Blog
    template_name='blog.html'
    context_object_name = 'blog'
    
class BlogCreateView(CreateView):
    model = Blog
    template_name = "create_blog.html"
    fields = '__all__'

class BlogUpdateView(UpdateView):
    model = Blog
    template_name = "update_blog.html"
    fields = ['title', 'body']
    
class BlogDeleteView(DeleteView):
    model = Blog
    template_name = "delete_blog.html"
    success_url = reverse_lazy('home') #so that it won't execute the url until the view has finished

blog/templates/base.html
<!doctype html>
<html>
    <head>
        <title>
            {% block title %}{% endblock title %}
        </title>
    </head>
    <body>
        <header>
            <a href="{% url 'home' %}">All blogs</a>
        </header>
        {% if user.is_authenticated %}
        <p>Hi {{user.username}}</p>
        <p><a href="{% url 'logout' %}">Log out</a></p>
        {% else %}
        <p>You are not logged in..Please<a href="{% url 'login' %}">Log in</a></p>
        <p>Or <a href="{% url 'accounts:signup' %}">Sign up</a></p>
        {% endif %}
        {% block content %}
        
        {% endblock content %}
    </body>
</html>

blog/templates/blog.html
{% extends 'base.html' %}
{% block title %}
{{blog.title}}
{% endblock title %}
{% block content %}
<h2>{{blog.title}}</h2>
<p>{{blog.body}}</p>
<a href="{% url 'update' blog.id %}">Update</a> | 
<a href="{% url 'delete' blog.id %}">Delete</a>
{% endblock content %}

blog/templates/create_blog.html
{% extends 'base.html' %}
{% block title %}
Create Blog
{% endblock title %}
{% block content %}
<form method='POSt'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='submit'>
</form>
{% endblock content %}

blog/templates/delete_blog.html
{% extends 'base.html' %}
{% block title %}
Delete Blog
{% endblock title %}
{% block content %}
<form method='post'>
    {% csrf_token %}
    <p>Are you sure you want to delete the blog: {{blog.title}}</p>
    <input type='submit' value='delete'>
</form>
{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}
{% block title %}
blog title
{% endblock title %}
{% block content %}
<ul>
    {% for blog in blogs %}
    <ul>
    <li><a href="{% url 'blog' blog.id%}">{{blog.title}}</a></li>
    <li>{{blog.author}}</li>
    <li>{{blog.body}}</li>
    <br>
    </ul>
    {% endfor %}
</ul>
<a href="{% url 'new_blog' %}">Add blog</a>

{% endblock content %}

blog/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit' >Submit</button>
</form>
{% endblock content %}

blog/templates/update_blog.html
{% extends 'base.html' %}
{% block title %}
Update blog
{% endblock title %}
{% block content %}
<form method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value='Update'>
</form>
{% endblock content %}